name: Check code format

on:
  push:
    branches:
      - feature/*/main
      - staging

jobs:
  lint:
    uses: ./.github/workflows/_build.yml
    with:
      lint-only: true
    secrets:
      REPO_PERSONAL_ACCESS_TOKEN: ${{ secrets.REPO_PERSONAL_ACCESS_TOKEN }}
      TINA_CLIENT_ID: ${{ secrets.TINA_CLIENT_ID }}
      TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
